Update compile_node

diff --git a/bin/compile_node b/bin/compile_node
--- a/bin/compile_node
+++ b/bin/compile_node
@@ -61,11 +61,7 @@ test -d $cache_dir/node/node_modules && modules_cached=true || modules_cached=fa
 ####### Provide debugging info and feedback
 
 echo ""
-info "Node engine:         ${
-
-
-
-:-unspecified}"
+info "Node engine:         ${node_engine:-unspecified}"
 info "Npm engine:          ${npm_engine:-unspecified}"
 info "Start mechanism:     ${start_method:-none}"
 info "node_modules source: ${modules_source:-none}"
@@ -173,7 +169,103 @@ fi
 head "Finalizing build"
 
 # Runtime & Multi-buildpack exports
-info "Creating runtime environment"
+info "Creating runtime environment"#!/usr/bin/env bash
+2
+# USAGE: bin/compile_node <build-dir> <cache-dir> <env-dir>
+3
+​
+4
+####### Configure environment
+5
+​
+6
+set -e            # fail fast
+7
+set -o pipefail   # don't ignore exit codes when piping output
+8
+# set -x          # enable debugging
+9
+​
+10
+# Configure directories
+11
+build_dir=$1
+12
+cache_dir=$2
+13
+env_dir=$3
+14
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
+15
+heroku_dir=$build_dir/.heroku
+16
+mkdir -p $heroku_dir/node
+17
+​
+18
+# Load some convenience functions like status(), echo(), and indent()
+19
+source $bp_dir/bin/common.sh
+20
+​
+21
+# Avoid GIT_DIR leak from previous build steps
+22
+unset GIT_DIR
+23
+​
+24
+# Provide hook to deal with errors
+25
+trap build_failed ERR
+26
+​
+27
+# Load config vars into environment; start with defaults
+28
+export NPM_CONFIG_PRODUCTION=true
+29
+export NODE_MODULES_CACHE=true
+30
+export_env_dir $env_dir
+31
+​
+32
+####### Determine current state
+33
+​
+34
+# What's the requested semver range for node?
+35
+#node_engine=$(package_json ".engines.node")
+36
+# Node version is locked for now: newer ones don't work with Meteor.
+37
+node_engine="4.5.0"
+38
+node_previous=$(file_contents "$cache_dir/node/node-version")
+39
+​
+40
+# What's the requested semver range for npm?
+41
+npm_engine=$(package_json ".engines.npm")
+42
+npm_previous=$(file_contents "$cache_dir/node/npm-version")
+43
+​
+44
+# How does this app start?
+45
+if test -f $build_dir/Procfile; then start_method="Procfile"
+46
+elif [[ $(package_json ".scripts.start") != "" ]]; then start_method="npm start"
+47
+elif [ -f $build_dir/server.js ]; then start_method="server.js"
+48
+else start_method=""
+49
+fi
 mkdir -p $build_dir/.profile.d
 echo "export PATH=\"\$HOME/.heroku/node/bin:\$HOME/bin:\$HOME/node_modules/.bin:\$PATH\"" > $build_dir/.profile.d/nodejs.sh
 echo "export NODE_HOME=\"\$HOME/.heroku/node\"" >> $build_dir/.profile.d/nodejs.sh
